//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1App.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Race()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int RaceId { get; set; }
        public int RaceSeason { get; set; }
        public int RaceRound { get; set; }
        public string RaceUrl { get; set; }
        public string RaceName { get; set; }
        public int CircuitId { get; set; }
        public string RaceDate { get; set; }
        public string RaceTime { get; set; }
    
        public virtual Circuit Circuit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
    }
}
