//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1App.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Pilots = new HashSet<Pilot>();
            this.TeamStandings = new HashSet<TeamStanding>();
        }
    

        public int TeamId { get; set; }
        [Required(ErrorMessage = "Enter Team Name")]
        [Display(Name = "Name")]
        public string TeamName { get; set; }
        [Required(ErrorMessage = "Enter team Nationality")]
        [Display(Name = "Nationality")]
        public string TeamNationality { get; set; }
        [Display(Name = "Url")]
        public string TeamUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pilot> Pilots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamStanding> TeamStandings { get; set; }
    }
}
