//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1App.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStanding
    {
        public int StandingId { get; set; }
        public int StandingSeason { get; set; }
        public int StandingPosition { get; set; }
        public int StandingPoints { get; set; }
        public int StandingWins { get; set; }
        public int TeamId { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
